import os
import re
import tempfile
from datetime import datetime


def _clean(text: str) -> str:
    """Strip leading/trailing whitespace and provide a fallback for empty sections."""
    text = (text or "").strip()
    return text if text else "_Not available._"


def build_report_markdown(session_state, summary, explanation, analogy, bugs, improvements, docs, complexity) -> str:

    code = session_state.get("last_code", "") or ""
    language = session_state.get("last_language", "") or "Unknown"
    level = session_state.get("last_level", "") or "—"
    mode = session_state.get("last_mode", "") or "—"
    qa_log = session_state.get("qa_log", []) or []

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    fence_lang = re.sub(r"[^a-zA-Z+]", "", language).lower() or "text"

    parts = [
        "# 💻 CodeMentor Report",
        f"_Generated {timestamp}_",
        "",
        f"**Language:** {language}  ",
        f"**Mode:** {mode}  ",
        f"**Explanation Level:** {level}",
        "",
        "## Original Code",
        f"```{fence_lang}",
        code if code.strip() else "(no code provided)",
        "```",
        "",
        "## 📝 Summary",
        _clean(summary),
        "",
        "## 📖 Explanation",
        _clean(explanation),
        "",
        "## 🌍 Real World Analogy",
        _clean(analogy),
        "",
        "## 🐞 Potential Bugs",
        _clean(bugs),
        "",
        "## 💡 Improvements",
        _clean(improvements),
        "",
        "## 📚 Documentation",
        _clean(docs),
        "",
        "## 📊 Complexity",
        _clean(complexity),
        "",
    ]

    if qa_log:
        parts.append("## 💬 Follow-up Questions")
        parts.append("")
        for i, qa in enumerate(qa_log, start=1):
            parts.append(f"**Q{i}: {qa['question']}**")
            parts.append("")
            parts.append(_clean(qa.get("answer", "")))
            parts.append("")
    else:
        parts.append("## 💬 Follow-up Questions")
        parts.append("")
        parts.append("_No follow-up questions were asked in this session._")
        parts.append("")

    parts.append("---")
    parts.append("Generated by CodeMentor 💻")

    return "\n".join(parts)


def generate_report_file(session_state, summary, explanation, analogy, bugs, improvements, docs, complexity) -> str:
    """Writes the report to a temp .md file and returns its path, for gr.File to serve."""

    content = build_report_markdown(
        session_state, summary, explanation, analogy, bugs, improvements, docs, complexity
    )

    filename = f"codementor_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    filepath = os.path.join(tempfile.gettempdir(), filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    return filepath